# site settings
title: Pascal Lola
subtitle: User Experience Designer, Researcher, Collaborator, Leader
email: lola.pascal@gmail.com
description: I design how humans interact with digital technology. I previously designed for the election industry. I currently design for the oil and gas industry. I hope to design for the future next. I love messy and complex problems. I love multidisciplinary teams. I champion collaboration. Letâ€™s talk. 
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

phone: (317) 658-5858

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: https://500px.com/tresor
facebook_url:
github_url: http://github.com/ptlola
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/pascalphotographs
linkedin_url: https://www.linkedin.com/in/ptlola/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/pascal_ux

# build settings
markdown: kramdown

sass:
  style: compressed
